[package]
name = "rp2040-usb-cdc"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[profile.release]
debug = 2       # Mantém símbolos de debug mesmo na build otimizada
opt-level = 1 # Otimiza fortemente para tamanho de binário
lto = false   

[dependencies]
# Required runtime boot architecture
cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"
static_cell = "2.1.0"
portable-atomic = { version = "1.0", features = ["critical-section"] }
smart-leds = "0.4.0"
defmt = "0.3.8"
defmt-rtt = "0.4.1"
fixed = "1.23.1"
fixed-macro = "1.2"
panic-probe = { version = "0.3.2", features = ["print-defmt"] }
libm = "0.2.16"
embedded-io-async = "0.7.0"

# Embassy crates
embassy-rp = { git = "https://github.com/HenriqueDomiciano/embassy", branch = "feat/add-pio-baud-rate-update", features = ["defmt", "time-driver", "critical-section-impl", "rp2040"] }

embassy-executor = { git = "https://github.com/HenriqueDomiciano/embassy", branch = "feat/add-pio-baud-rate-update", features = [
    "executor-thread",
    "platform-cortex-m",
    "defmt",
] }

embassy-time = { git = "https://github.com/HenriqueDomiciano/embassy", branch = "feat/add-pio-baud-rate-update", features = [
    "defmt",
    "defmt-timestamp-uptime",
] }

embassy-usb = { git = "https://github.com/HenriqueDomiciano/embassy", branch = "feat/add-pio-baud-rate-update", features = [
    "defmt",
    "max-interface-count-8",
] }

embassy-futures = { git = "https://github.com/HenriqueDomiciano/embassy", branch = "feat/add-pio-baud-rate-update" }

embassy-embedded-hal = { git = "https://github.com/HenriqueDomiciano/embassy", branch = "feat/add-pio-baud-rate-update" }

embassy-sync = { git = "https://github.com/HenriqueDomiciano/embassy", branch = "feat/add-pio-baud-rate-update" }

[package.metadata.embassy_rp]
task_arena_size = 65536