[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip rp2040 --rtt-scan-memory"
rustflags = [
  "-C",
  "link-arg=-Tlink.x",
]
[env]
# 3 CDC channels * 2 interfaces per channel = 6 interfaces minimum
EMBASSY_USB_MAX_INTERFACE_COUNT = "8"

# 3 CDC channels * 3 endpoints per channel = 9 endpoints minimum
EMBASSY_USB_MAX_HANDLER_COUNT = "12"
DEFMT_LOG = "debug"

[alias]
test-host = "rustc -- --edition 2021 tests/unit_tests.rs --test -o /tmp/unit_tests && /tmp/unit_tests"
